swagger: "2.0"
info:
  version: "0.0.1"
  title: Review App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /v1/
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https

# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

paths:
  /User/Login:
    x-swagger-router-controller: user
    post:
      description: Login user to access protected api endpoints
      operationId: login
      security: [] #removes bearer security from endpoint
      parameters:
        - in: body
          name: payload
          description: User's login email address and password.
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /User/Information:
    x-swagger-router-controller: user
    get:
      description: Fetch information for current logged in user
      operationId: information
      security:
        - Bearer: []
      x-security-scopes:
        - company
        - group
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /User/ChangePassword:
    x-swagger-router-controller: user
    post:
      description: Change users password
      operationId: changePassword

      security:
        - Bearer: []
      x-security-scopes:
        - company
        - group
      parameters:
        - in: body
          name: payload
          description: Old password and new password
          schema:
            type: object
            required:
              - oldPassword
              - newPassword
            properties:
              oldPassword:
                type: string
              newPassword:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /Configuration:
    x-swagger-router-controller: common
    get:
      description: Fetch general configuration information
      operationId: configuration
      security:
        - Bearer: []
      x-security-scopes:
        - company
        - group
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /Campaigns:
    x-swagger-router-controller: campaigns
    get:
      description: Returns list of campaigns
      operationId: getCampaigns
      security:
        - Bearer: []
      x-security-scopes:
        - company
        - group
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /Campaigns/{id}/Commence:
    x-swagger-router-controller: campaigns
    get:
      description: Commences a campaign
      operationId: commenceCampaign
      parameters:
        - in: path
          name: id
          description: Numeric id of the campaign to fetch.
          required: true
          type: integer
      security:
        - Bearer: []
      x-security-scopes:
        - company
        - group
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /Campaigns/{id}:
    x-swagger-router-controller: campaigns
    get:
      description: Returns a campaigns detailed information
      operationId: getCampaignDetail
      parameters:
        - in: path
          name: id
          description: Numeric id of the campaign to fetch.
          required: true
          type: integer
      security:
        - Bearer: []
      x-security-scopes:
        - company
        - group
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /Other/RecipientsFromFile:
    x-swagger-router-controller: other
    post:
      description: Fetch list of recipients from uploaded csv
      operationId: recipientsFromFile
      security:
        - Bearer: []
      x-security-scopes:
        - company
        - group
      parameters:
        - in: body
          name: payload
          description: CSV file with name and email columns
          schema:
            type: object
            required:
              - file
            properties:
              file:
                type: string
                format: binary
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /diary/entries:
    x-swagger-router-controller: diary
    get:
      description: Returns list of diary entries for a specific day
      operationId: diaryEntries
      security:
        - Bearer: []
      parameters:
        - in: query
          name: date
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /diary/staff-roster:
    x-swagger-router-controller: diary
    get:
      description: Returns list of staff rosters for a specific day
      operationId: diaryStaffRoster
      security:
        - Bearer: []
      parameters:
        - in: query
          name: date
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /diary/entries/add:
    x-swagger-router-controller: diary
    post:
      description: Adds a diary entry
      operationId: diaryEntriesAdd
      security:
        - Bearer: []
      parameters:
        - in: body
          name: entryData
          description: Type, Staff Member, Start and End times.
          schema:
            type: object
            required:
              - type
              - startTime
              - endTime
              - staffId
            properties:
              type:
                type: string
              staffId:
                type: integer
              startTime:
                type: string
              endTime:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /diary/entries/remove:
    x-swagger-router-controller: diary
    post:
      description: Removes an entry from the diary
      operationId: diaryEntriesRemove
      security:
        - Bearer: []
      parameters:
        - in: body
          name: entryData
          description: entryId, type, start time, end time
          schema:
            type: object
            properties:
              entryId:
                type: string
              staffId:
                type: integer
              type:
                type: string
              startTime:
                type: string
              endTime:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /groups/{id}:
    x-swagger-router-controller: groups
    get:
      description: Returns a specific group's information.
      operationId: getGroup
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the group to get.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /groups/{id}/companies:
    x-swagger-router-controller: groups
    get:
      description: Returns all companies in a specific group.
      operationId: getGroupCompanies
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the group to get.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /services/categories:
    x-swagger-router-controller: services
    get:
      description: Returns a list of all active services
      operationId: getServiceCategories
      security:
        - Bearer: []
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
    # post: // insert
    # patch: // update
    # delete: // delete

  /services/categories/{id}:
    x-swagger-router-controller: services
    get:
      description: Returns a service category by id
      operationId: getServiceCategory
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the service category to get.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /services/categories/{id}/templates:
    x-swagger-router-controller: services
    get:
      description: Returns templates of a specific service category
      operationId: getServiceCategoryTemplates
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the service category.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /services/categories/{id}/services:
    x-swagger-router-controller: services
    get:
      description: Returns services of a specific service category
      operationId: getServiceCategoryServices
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the service category.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /services/templates:
    x-swagger-router-controller: services
    get:
      description: Returns all services templates
      operationId: getServiceTemplates
      security:
        - Bearer: []
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /services/templates/{id}:
    x-swagger-router-controller: services
    get:
      description: Returns specific service template
      operationId: getServiceTemplate
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the service template.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /services/templates/{id}/services:
    x-swagger-router-controller: services
    get:
      description: Returns a list of services of a specific service template
      operationId: getServiceTemplateServices
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the service template.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /services:
    x-swagger-router-controller: services
    get:
      description: Returns a list of all services
      operationId: getServices
      security:
        - Bearer: []
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /services/{id}:
    x-swagger-router-controller: services
    get:
      description: Returns a sepcific service
      operationId: getService
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the service.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /clients/search/{query}:
    x-swagger-router-controller: clients
    get:
      description: Returns a clients who match search string
      operationId: searchClients
      security:
        - Bearer: []
      parameters:
        - in: path
          name: query
          description: Search query.
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /clients/{id}/episodes:
    x-swagger-router-controller: clients
    get:
      description: Returns a list of episodes belonging to a client
      operationId: clientEpisodes
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Client ID
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"

  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  GenericSuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  GenericErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
