swagger: "2.0"
info:
  version: "0.0.1"
  title: Practice App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https

# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
     
paths:
  

  /login:
    x-swagger-router-controller: staff
    post:
      description: Login user to access protected api endpoints
      operationId: staffLogin
      security: [] #removes bearer security from endpoint
      parameters:
        - in: body
          name: credentials
          description: User's login email address and password.
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
    # post: // insert
    # patch: // update
    # delete: // delete



  /services/categories:
    x-swagger-router-controller: services
    get:
      description: Returns a list of all active services
      operationId: getServiceCategories
      security:
        - Bearer: []
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
    # post: // insert
    # patch: // update
    # delete: // delete
  /services/categories/{id}:
    x-swagger-router-controller: services
    get:
      description: Returns a service category by id
      operationId: getServiceCategory
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the service category to get.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /services/categories/{id}/templates:
    x-swagger-router-controller: services
    get:
      description: Returns templates of a specific service category
      operationId: getServiceCategoryTemplates
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the service category.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /services/categories/{id}/services:
    x-swagger-router-controller: services
    get:
      description: Returns services of a specific service category
      operationId: getServiceCategoryServices
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the service category.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"            
  /services/templates:
    x-swagger-router-controller: services
    get:
      description: Returns all services templates
      operationId: getServiceTemplates
      security:
        - Bearer: []
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /services/templates/{id}:
    x-swagger-router-controller: services
    get:
      description: Returns specific service template
      operationId: getServiceTemplate
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the service template.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /services/templates/{id}/services:
    x-swagger-router-controller: services
    get:
      description: Returns a list of services of a specific service template
      operationId: getServiceTemplateServices
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the service template.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /services:
    x-swagger-router-controller: services
    get:
      description: Returns a list of all services
      operationId: getServices
      security:
        - Bearer: []
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /services/{id}:
    x-swagger-router-controller: services
    get:
      description: Returns a sepcific service
      operationId: getService
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          description: Numeric id of the service.
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenericSuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/GenericErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  GenericSuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  GenericErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
